### ISSUE TITLE
Missing executable

### ISSUE THREAD

**Issue by Diogenes2023** [AthenaADP/MHFU-ASS#1]
Hi Athena, I'm really, really sorry for not using the issue reporting function properly.
I just see no releases for the ASS MHFU version and no executable in the zip file.
I'm guessing I should either compile one myself or import the data folder and overwrite it in the ASS v3.42b folder (which I have) and run that executable using the (maybe) new data?
Again sorry for asking, but am I seeing it wrong and the new ASS project for MHFU does contain an .exe file and I'm just too thick/dumb to find it here?:
https://github.com/AthenaADP/MHFU-ASS

Cheers!

**Comment by AthenaADP** [comment]
This site is just for the source code, which you can compile yourself if you want.

But if you just want the exe, you can download all my MonHun ASS apps from my shared drive: https://drive.google.com/drive/folders/1zJBCM5QIefUp8-AufMRHuTJpWFMoOkYn
